#ifndef __PARAMS__H_
#define __PARAMS__H_

// DISPLAY
#define DISPLAY_ON

// STARTLINE CHECK

// range: 0 - 1000
#define START_LINE_VECTORS_ACCEPTED_LENGHT_MINDIF 400U
// range: 0 - 1000
#define START_LINE_VECTORS_ACCEPTED_ANGLE_HORIZ 400U
// range: 0 - 51
#define START_LINE_VECTORS_ACCEPTED_HEIGHT_DELTA 11U

#endif // __PARAMS__H_
